'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');
const {startClock,settleClock}=require('../game/clock');const {validatePresence}=require('../game/presence');const E=require('../game/engine');
const initial=()=>E.createGame({phase:'setup',ready:[true,true],tanks:[[2,1,1,1],[2,1,1,1]],firstRoll:{dice:[6,2],winner:0}},n=>n-1);
test('persisted starting roll determines turn order, without rerandomizing it at start',()=>{const s=initial();assert.deepEqual(s.order,[0,1]);assert.deepEqual(s.firstRoll.dice,[6,2]);});
test('overtime transfers only completed extra minutes, allows debt, survives reload, and resets each turn',()=>{
  let s=initial();s.players[0].cash=2;startClock(s,1000);assert.equal(settleClock(s,360999),0);assert.equal(settleClock(s,361000),5);assert.equal(s.players[0].cash,-3);assert.equal(s.players[1].cash,45);
  s=JSON.parse(JSON.stringify(s));assert.equal(settleClock(s,361000),0);assert.equal(settleClock(s,481000),10);assert.equal(s.players[0].cash,-13);assert.equal(s.players[1].cash,55);
  s=E.applyAction(s,0,{type:'skip'});s=E.applyAction(s,0,{type:'end'});startClock(s,481000);assert.equal(s.clock.actor,1);assert.equal(settleClock(s,781000),0);s.phase='finished';assert.equal(settleClock(s,99999999),0);
});
test('a debt balance still permits free government upgrade benefits',()=>{let s=initial();s.players[0].cash=-5;s.bonuses=[{actor:0,source:'Government',governmentPipes:1,tanks:0,machines:0,shopPipes:0}];const id=s.government[0].tiles[0];s=E.applyAction(s,0,{type:'bonus',kind:'government',quadrant:0,indexes:[0],placements:[{id,x:0,y:0,rotation:0}]});assert.equal(s.players[0].cash,-5);});
test('view relay accepts bounded public previews and rejects injection, oversized or malformed data',()=>{const v={left:'actions',right:'refinery-1',overview:false,click:'left|data-panel-tab|government',draft:{type:'work',space:'government',indexes:[0],placements:[]}};assert.equal(validatePresence(v).left,'actions');for(const bad of [{...v,left:'credentials'},{...v,draft:{tile:'<img src=x onerror=alert(1)>'}},{...v,draft:{placements:Array(130).fill(null)}},{...v,click:'x'.repeat(200)},{...v,scroll:JSON.parse('{"__proto__":{}}')}])assert.throws(()=>validatePresence(bad));});
test('asset-only scoring counts oil and pipelines once and retains the separate machine tile',()=>{const s=initial();s.players[0].oil=[{id:'o',color:'orange',grade:3}];E.score(s);assert.equal(s.scores[0].oil,30);assert.equal(s.scores[0].total,70);assert.equal(s.scores[0].valuation1+s.scores[0].valuation2+s.scores[0].valuation3,0);});
test('a single refined-market action can sell then buy with proceeds',()=>{let s=initial();s.players[0].cash=0;s.players[0].oil=[{id:'sale',color:'orange',grade:3}];const m=s.markets[1];const ri=m.rows.findIndex(r=>r.color==='orange'&&r.grade===1);m.rows[ri].slots[1].barrel={id:'purchase',color:'orange',grade:1};s=E.applyAction(s,0,{type:'work',space:m.id,transactions:[{kind:'sell',market:m.id,row:ri,slot:0,barrel:'sale'},{kind:'buy',market:m.id,row:ri,slot:1}]});assert.deepEqual(s.players[0].oil,[{id:'purchase',color:'orange',grade:1}]);assert.equal(s.turn.stage,'secondary');});
